[General]
SyntaxVersion=2
BeginHotkey=45
BeginHotkeyMod=8
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=4
RunOnce=1
EnableWindow=
MacroID=b3696cd3-1ae5-4c49-a4e9-10ff3986379c
Description=新增家庭参保人员
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 54, 169
LeftClick 1
LeftUp 1
'==========以上是按键精灵录制的内容==========
